export const mockcommonAddressData = {
  uid: '1',
  name: '张三',
  phone: '15960123456',
  address: '北京市丰台区大红门街道珠江骏景北区65号楼1120室'
}

export const mockOrderData = {
  id: '1',
  sponsor: '王五',
  thumbnail: 'http://img06.tooopen.com/images/20160818/tooopen_sy_175866434296.jpg',
  title: '山东水蜜桃1.2kg200g以上/个山东水蜜桃1.2kg200g以上/个',
  desc: '山东水蜜桃1.2kg200g以上/个山东水蜜桃1.2kg200g以上/个',
  price: '2680',
  number: 2,
  value: 5360,
  transport: '快递免邮'
}